import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Kiti bus App",
  description: "Generated by Vercel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="english">
      <body className="font-Inter-Regular">
          {children}
      </body>
    </html>
  );
}
