import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "./_component/SideBar";
import Navbar from "./_component/Navbar";
import NextTopLoader from "nextjs-toploader";
import { Session } from "@/lib/definitions";
import { getSession } from "@/lib/session";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  const session: Session = await getSession();

  return (
    <html lang="english">
      <body>
        {/* Top Loader */}
        <div className="z-[99999]">
          <NextTopLoader showSpinner={false} color="#b1dc30" />
        </div>

        {/* Navigation */}
        <Navbar session={session} />

        {/* Main content */}
        <main className="lg:pl-[250px] pt-0 lg:pt-[12vh]">
          {children}
        </main>

      </body>
    </html>
  );
}
